### PR TITLE
Django 2 compatibility

### PR DESCRIPTION
**Pull request by suchermon**
I have upgraded EWP to django 2 so I can use the latest of wagtail. Adding this to support django 1.11 and newer. Please review.

### CODE REVIEW

**Comment by theunraveler** [comment]
Thanks for tackling this, @suchermon . I did notice a small issue and that's that when you call methods, `self` needs to be the first parameter. So your method call wasn't actually doing anything with the `user` parameter in that function.

In any case, I changed the call in a few ways:
- Made it a property, since we don't need to pass the user to the method because the method already has access to `self.request.user`. Just makes it a little easier to call.
- Added double underscore prefix to indicate that it's a private method.
- Checked for the django version instead of `callable`. I think this makes it clearer that this code is here to handle django backwards compatibility instead of just some random case where the attribute could be callable or not.

Thanks, and let me know if this makes sense or if you have any thoughts or questions.

**Comment by suchermon** [comment]
Sounds good!

**Comment by suchermon** [comment]
ok to merge? So I can pull the latest into EWP project

**Comment by theunraveler** [comment]
I think so :+1:

**Pull request merged**
